### ISSUE TITLE
Compile with en_GB dictionaries?

### ISSUE THREAD

**Issue by alkanegit** [AnthonyTerra/ASP.MVC-Jquery-Spellchecker#3]
Hi.  Please can you advise how to compile with UK English spelling instead of US?

Thanks in advance!

**Comment by AnthonyTerra** [comment]
Take a look at the SpellingProxy.cs.  you could add an additional dictionary folder for engb and add the appropriate language modifier for the the language enumeration.

**Comment by alkanegit** [comment]
Thank you Anthony.  I did just that.  I got hold of the en_GB dictionary files, added a folder called 'en_GB' and literally did a find/replace on 'en_US' with 'en_GB', compiled, and viola!  Great work.

**Comment by AnthonyTerra** [comment]
Great glad that worked.
